import { X, Download, FileText } from 'lucide-react';

interface Props {
  documentName: string;
  documentType: string;
  sellerName?: string;
  sellerBusiness?: string;
  product?: string;
  destination?: string;
  onClose: () => void;
}

export default function DocumentPreview({ documentName, documentType, sellerName, sellerBusiness, product, destination, onClose }: Props) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={onClose}>
      <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between p-4 border-b border-gray-200">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-[var(--color-primary)]" />
            <h3 className="font-semibold text-gray-900">{documentName}</h3>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handlePrint} className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium bg-[var(--color-primary)] text-white rounded-lg hover:bg-gray-800 transition-colors">
              <Download className="h-3.5 w-3.5" /> Print / Save PDF
            </button>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="p-8" id="document-preview">
          <div className="text-center border-b-2 border-[var(--color-primary)] pb-6 mb-6">
            <p className="text-xs text-gray-500 uppercase tracking-widest">Government of India</p>
            <h1 className="text-xl font-bold text-[var(--color-primary)] mt-2">{documentType}</h1>
            <p className="text-xs text-gray-400 mt-1">Niryat Saathi — Digital Export Enablement Platform</p>
          </div>

          <div className="space-y-4 text-sm">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-gray-500 uppercase">Document Reference</p>
                <p className="font-medium text-gray-900">NS-{Date.now().toString().slice(-8)}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase">Date of Issue</p>
                <p className="font-medium text-gray-900">{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
              </div>
            </div>

            {sellerName && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-gray-500 uppercase">Applicant</p>
                  <p className="font-medium text-gray-900">{sellerName}</p>
                  {sellerBusiness && <p className="text-xs text-gray-600">{sellerBusiness}</p>}
                </div>
                {destination && (
                  <div>
                    <p className="text-xs text-gray-500 uppercase">Destination</p>
                    <p className="font-medium text-gray-900">{destination}</p>
                  </div>
                )}
              </div>
            )}

            {product && (
              <div>
                <p className="text-xs text-gray-500 uppercase">Product</p>
                <p className="font-medium text-gray-900">{product}</p>
              </div>
            )}
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200 text-center">
            <p className="text-xs text-gray-400">
              This is a prototype document generated by Niryat Saathi for demonstration purposes only.
              <br />This document is not legally binding.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
